version: "3"
services:
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: nginx-prod.conf.template
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email thornhill52320@gmail.com --agree-tos --no-eff-email --expand -v
      -d stephentcasey.com -d landscape-patterns.stephentcasey.com
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
